fix: tag new versions only locally, push one by one

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -50,10 +50,13 @@ jobs:
         with:
           run-versioning: true
           publish-dry-run: true
-          tag: true
+          tag: false
           create-pr: false
         env:
           GH_TOKEN: ${{ steps.generate_token.outputs.token }}
+      - name: Create Tags Locally
+        # Tag packages after versioning, create new tags, don't fail on existing tags
+        run: melos exec -c 1 --no-private -- git tag \$MELOS_PACKAGE_NAME-v\$MELOS_PACKAGE_VERSION || true
       - name: Push Release Commit
         run: git push --no-follow-tags
       - name: Push Tags
